### PR TITLE
⬆️ zm,zv,zu: Update syn to v2.0.64

### LINKED ISSUE #401: Switch to syn2
Currently zbus/zvariant macros still depend on syn 1.0

### PR DESCRIPTION
**Pull request by zecakeh**
Built on top of and replaces #404.
Fixes #401.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
By using async-std (the async-attributes crate specifically) ends up pulling syn1... maybe it is worth investigating dropping the usage of async-std as is and use the sub-crates individually

**Comment by zeenix** [comment]
> By using async-std

It's only a dev dep so no biggie.

Sophie already tried to remove this dep and I [agreed with her what needed to be done](https://github.com/dbus2/zbus/pull/531#issuecomment-1872930834) but then she dropped the ball. 🤷‍♂️

**Review by zeenix — CHANGES_REQUESTED** [review]
Nice! Thanks for doing this work. Please also put the description to the commit. Then I can merge.

**Comment by zecakeh** [comment]
Done.

**Review by zeenix — APPROVED** [review]

**Pull request merged**
