### PR TITLE
Fix `println` in client.md

### PR DESCRIPTION
**Pull request by Jedsek**

### CODE REVIEW

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks but this is not a mistake. This is a general term.

**Comment by Jedsek** [comment]
@zeenix but... :)
image

**Comment by Jedsek** [comment]
I blame me for not making it clear. :)

**Comment by zeenix** [comment]
> @zeenix but... :)

Ah, there was a discrepancy.  

> I blame me for not making it clear. :)

No worries. I you had followed [our contributing guideline](https://github.com/dbus2/zbus/blob/main/CONTRIBUTING.md), it would have encouraged you to write more descriptive/details commit log. Although I won't enforce that for such a simple change but it would be good to make it clear. :)

**Review by zeenix — APPROVED** [review]

**Comment by Jedsek** [comment]
Thanks.

**Pull request merged**
