### PR TITLE
🚚 zb: Rename Error::QuickXml to Xml

### PR DESCRIPTION
**Pull request by zeenix**
We only have one kind if Xml error now.

### CODE REVIEW

**Comment by elmarco** [comment]
It's still an error from quick_xml though, .. what if we have our own Xml errors then?

**Comment by zeenix** [comment]
> It's still an error from quick_xml though,

Hmm.. yeah. I wasn't too sure about this change tbh. Just that I know users won't care about this fact and `Xml` is simpler to type.

> .. what if we have our own Xml errors then?

Not sure we'll want our own generic Xml error. We'll likely have more specific errors.

**Comment by elmarco** [comment]
I am not acking this, but if you feel strong about it, ok

**Comment by zeenix** [comment]
ok

**Pull request closed without merging**
