### PR TITLE
Some dependencies updates

### PR DESCRIPTION
**Pull request by elmarco**

### CODE REVIEW

**Comment by zeenix** [comment]
Thanks but did you see #636 and #643 ? The dependency updates have already been automated so if a dep hasn't been update, there is usually a reason.

**Comment by elmarco** [comment]
No, I didn't see those. And it's hard to see it's an api break.. why?

**Comment by zeenix** [comment]
> No, I didn't see those. And it's hard to see it's an api break.. why?

Because users of old tokio-vsock would not be able to build with newer zbus anymore, if they construct the connection using the socket. This can be avoided using a hack but given that I don't want hacks for vsock.

**Comment by zeenix** [comment]
So can we close this then?

**Pull request closed without merging**
