### PR TITLE
zv: Multiple lists support for derive macros.

### PR DESCRIPTION
**Pull request by turbocool3r**
This PR adds support for multiple attribute list identifiers to `def_attrs!` macro from `zvariant_utils` and uses this in `zvariant_derive` to avoid mentioning `zvariant` when using macros out of `zbus` (as described in #820).

### CODE REVIEW

**Comment by turbocool3r** [comment]
Looks like it's ready for review

**Comment by zeenix** [comment]
Cool. Still no emojis? :crying_cat_face: Could you please add those, it helps me as a very visual person to follow the history better and especially in writing release notes from the commit log. Emoji-less commits also look out of place in our git history now a days. :)

**Comment by zeenix** [comment]
Oh and `zu` is the prefix I've been using for `zvariant_utils`.

**Review by zeenix — COMMENTED** [review]
Awesome. Functionality wise, it looks great. Only nits about commit log of last commit. :laughing: 

* Could just be "zd: Allow `zbus` attribute in macros". This will fit in the 50 chars limit and is sufficient.
* It would be good to mention that this will make it possible to resolve #807.

**Comment by zeenix** [comment]
> Looks like it's ready for review

Indeed. Functionality wise, this is ready for merge. :)

**Comment by turbocool3r** [comment]
Just reworded everything, added emojis. Not sure if these are the best choice... I was only familiar with 🍻 gitmoji before 😄

**Comment by zeenix** [comment]
> Just reworded everything, added emojis. Not sure if these are the best choice... 

The're good, thanks! :) 

> I was only familiar with 🍻 gitmoji before 😄

I think the only person to have used that emoji so far, is @elmarco (85eb406f6363eabc8a8d6edca5aafd838675fae9).

**Pull request merged**
