### PR TITLE
Drop serde-xml, rename quick-xml feature

### PR DESCRIPTION
**Pull request by elmarco**
My initial plan was to make `xml` a different module, but I think this is not a good idea as I plan to add some dependencies on zbus.

### CODE REVIEW

**Comment by zeenix** [comment]
> My initial plan was to make `xml` a different module,

Do you mean sub-crate?

> as I plan to add some dependencies on zbus

Not sure I follow. :thinking:

**Comment by elmarco** [comment]
> > My initial plan was to make `xml` a different module,
> 
> Do you mean sub-crate?

yeah a different crate

> 
> > as I plan to add some dependencies on zbus
> 
> Not sure I follow. thinking

I would like the introspection tree to provide better typed members. There is InterfaceName, MemberName, but we could have more. Not sure if they are all covered by non-zbus crates. I want to avoid a circular deps... Furthermore, I wonder still if we may want to build a introspection tree instead of just plain-text xml...

**Comment by elmarco** [comment]
In the meantime, we can merge this I suppose.

**Comment by zeenix** [comment]
> I would like the introspection tree to provide better typed members. There is InterfaceName, MemberName, but we could have more. Not sure if they are all covered by non-zbus crates. I want to avoid a circular deps... Furthermore, I wonder still if we may want to build a introspection tree instead of just plain-text xml...

Thanks.

> In the meantime, we can merge this I suppose.

Sure.

**Review by zeenix — APPROVED** [review]

**Pull request merged**
